server:
  port: 8081

spring:
#  profiles:
#    active: prod  --for changing the application-prod.yml from GitHub
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useSSL=false&serverTimezone=UTC
    username : root
    password : 123456
    #driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto : update
    show-sql : true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:configserver:http://localhost:8085 #for connecting the configServer which connects its properties to GitHub

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-86441457.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaazqc1yj7IN5pe55d7
            client-secret: 9c2N50mzK-upoMzCgISec4G01b3Lkmy1qCIc2Vc1mG1t26WbYs_3JdCcKqVxRAve
        provider:
          okta:
            issuerUri: https://dev-86441457.okta.com/oauth2/default

#eureka :
#  instance:
#    prefer-ip-address : true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url :
#      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10

  retry:
    instances:
      ratingHotelRetry:
        waitDuration: 5s
        maxAttempts: 3

  ratelimiter:
    instances:
      ratingHotelLimiter:
        timeoutDuration: 2s
        limitRefreshPeriod: 4s
        limitForPeriod: 2  #allow 2 user in 4s

okta:
  oauth2:
    issuer: https://dev-86441457.okta.com/oauth2/default
    audience: api://default




